# Generated by Django 5.1.15 on 2026-08-20 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id_adherant', models.AutoField(primary_key=True, serialize=False)),
                ('mecano', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('unite', models.CharField(max_length=150)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('id_statut', models.ForeignKey(db_column='id_statut', on_delete=django.db.models.deletion.PROTECT, to='referentiels.statut')),
            ],
            options={
                'db_table': 'adherant',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('gestionnaire', 'Gestionnaire'), ('officier', 'Officier')], default='officier', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_adherant', models.OneToOneField(db_column='id_adherant', on_delete=django.db.models.deletion.PROTECT, related_name='utilisateur', to='accounts.adherent')),
            ],
            options={
                'db_table': 'utilisateur',
            },
        ),
    ]
