# Generated by Django 5.1.15 on 2026-08-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('TRESORIER', 'Trésorier'), ('OFFICIER', 'Officier')], default='OFFICIER', max_length=20),
        ),
    ]
