# Generated by Django 5.1.15 on 2026-08-20 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_memberprofile'),
        ('referentiels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=30, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('date_adhesion', models.DateField(blank=True, null=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adherents', to='referentiels.grade')),
                ('lieu_naissance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adherents_nes', to='referentiels.ville')),
                ('statut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adherents', to='referentiels.statut')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adherents', to='referentiels.unite')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adherent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['matricule'],
            },
        ),
    ]
