# Generated by Django 5.1.15 on 2026-08-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('TRESORIER', 'Trésorier'), ('SUPERIEUR', 'Supérieur'), ('OFFICIER', 'Officier')], default='OFFICIER', max_length=20),
        ),
    ]
