# Generated by Django 6.1 on 2026-08-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('TRESORIER', 'Trésorier'), ('OFFICIER', 'Officier')], default='OFFICIER', max_length=20),
        ),
    ]
