# Generated by Django 5.1.15 on 2026-08-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mecano',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='statut',
            field=models.CharField(blank=True, choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('RETRAITE', 'Retraité')], default='ACTIF', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='unite',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
