# Generated by Django 5.1.15 on 2026-08-20 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cotisation', 'Cotisation'), ('pret', 'Prêt'), ('remboursement', 'Remboursement')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('attente', 'En attente'), ('valide', 'Validée'), ('refuse', 'Refusée')], default='attente', max_length=20)),
                ('operation_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-operation_date', '-created_at'],
                'indexes': [models.Index(fields=['member', 'type'], name='operations__member__fae5b4_idx'), models.Index(fields=['member', 'status'], name='operations__member__74f8de_idx')],
            },
        ),
    ]
