# Generated by Django 5.1.15 on 2026-08-20 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adherent'),
        ('operations', '0001_initial'),
        ('referentiels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='adherent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='accounts.adherent'),
        ),
        migrations.AddField(
            model_name='operation',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='referentiels.etablissement'),
        ),
        migrations.AddField(
            model_name='operation',
            name='etat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='referentiels.etat'),
        ),
        migrations.AddField(
            model_name='operation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='referentiels.service'),
        ),
        migrations.CreateModel(
            name='OperationPerso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_personnelles', to='accounts.adherent')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operation_perso', to='operations.operation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations_personnelles_creees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
