# Generated by Django 5.1.15 on 2026-08-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_pret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='etat',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
