# Generated by Django 5.1.15 on 2026-08-21 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_alter_pret_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_remboursement', models.DateField(auto_now_add=True)),
                ('mode_paiement', models.CharField(max_length=30)),
                ('observation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='remboursements', to='operations.pret')),
            ],
            options={
                'ordering': ['-date_remboursement'],
            },
        ),
    ]
