# Generated by Django 5.1.15 on 2026-08-25 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_remboursement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remboursement',
            name='date_remboursement',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
