# Generated by Django 5.1.15 on 2026-08-20 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0002_operation_adherent_operation_etablissement_and_more'),
        ('referentiels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(max_length=100)),
                ('consommation', models.BooleanField(default=False)),
                ('mise_a_jour', models.BooleanField(default=False)),
                ('suppression', models.BooleanField(default=False)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('etat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='referentiels.etat')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='operations.operation')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_operation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_operation'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=100)),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('type_modification', models.CharField(max_length=50)),
                ('donnees_avant', models.JSONField(blank=True, default=dict)),
                ('donnees_apres', models.JSONField(blank=True, default=dict)),
                ('id_user', models.BigIntegerField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_heure'],
            },
        ),
    ]
