# Generated by Django 5.1.15 on 2026-08-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_etablissement', models.CharField(max_length=150, unique=True)),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('type_etablissement', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_etat', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_grade', models.CharField(max_length=100, unique=True)),
                ('echelon', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['libelle_grade'],
            },
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_pays', models.CharField(max_length=100, unique=True)),
                ('code_iso', models.CharField(max_length=3, unique=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['libelle_pays'],
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_statut', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type_service', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_service', models.CharField(max_length=150, unique=True)),
                ('description_service', models.CharField(blank=True, max_length=255)),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='referentiels.typeservice')),
            ],
            options={
                'ordering': ['libelle_service'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villes', to='referentiels.pays')),
            ],
            options={
                'ordering': ['libelle_ville'],
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_unite', models.CharField(max_length=150, unique=True)),
                ('adresse_unite', models.CharField(blank=True, max_length=255)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unites', to='referentiels.ville')),
            ],
            options={
                'ordering': ['libelle_unite'],
            },
        ),
        migrations.AddConstraint(
            model_name='ville',
            constraint=models.UniqueConstraint(fields=('pays', 'libelle_ville'), name='unique_ville_pays'),
        ),
    ]
