# Generated by Django 5.1.15 on 2026-08-20 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde_actuel', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('type_etablissement', models.CharField(max_length=100)),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('echelon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_pays', models.CharField(max_length=100)),
                ('indicatif', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_service', models.CharField(max_length=150)),
                ('description_service', models.TextField(blank=True, null=True)),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='referentiels.typeservice')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_ville', models.CharField(max_length=150)),
                ('code_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villes', to='referentiels.pays')),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_unite', models.CharField(max_length=150)),
                ('adresse_unite', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites', to='referentiels.ville')),
            ],
        ),
    ]
